### ISSUE TITLE
Feedback Lab 2

### ISSUE THREAD

**Issue by hdmeyer** [software-engineering-amsterdam/ST2017_WG_3#3]
Group # | Exercise 1 | Comments | Exercise 2 | Comments | Exercise 3 | Comments | Exercise 4 | Comments | Exercise 5 | Comments | Exercise 6 | Comments | Exercise 7 | Comments | Exercise 8 | Comments | Total
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
3 | 9 | Well implemented and tested. A pity that you did not report the time spent | 9 | Well implemented, no time reporting | 10 | data.list had already a sort function | 8 | No info about the ordering of properties. | 8 | No timing. No answer for the question:Can you automate the test process? | 6 | No quickcheck.Unclear definition of rot13 | 9 | Great solution, not time reporting | 0 |   | 8.43
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --

**Comment by stemis** [comment]
@hdmeyer 

Thank you for providing feedback.

We did not know we needed to provide timing on the group solution.
After we received the feedback from Lab1, we added them to the solution yesterday.

I hope you could recheck the solution?

Also, could you re-check the grading?
I believe exercise 8 is bonus, therefore it should not be included in the grading
9 + 9 + 10 + 8 + 8 + 6 + 9 = 59
59 / **7** = 8.4

Thank you,

**Comment by hdmeyer** [comment]
Thanks for pointing it out. Corrected now.
