### ISSUE TITLE
Feedback Lab 5

### ISSUE THREAD

**Issue by hdmeyer** [software-engineering-amsterdam/ST2017_WG_3#7]
Group # | Exercise 1 | Comments | Exercise 2 | Comments | Exercise 3 | Comments | Exercise 4 | Comments | Exercise 5 | Comments | Exercise 6 | Comments | Exercise 7 | Comments | Total
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
3 | 9 | Why subgridSurjectIve? Define subgridNrcInjective instead. This is unneccesary complicated. | 6 | blocks will still be used in bl, prune can be much simpler. | 6 | Good work. No random deletion of hints. No test report | 6 | Analysis of how to remove more than 3 blocks is missing | 10 | Excellent | 0 | No solution provided | 0 |   | 7.4
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --

**Comment by EdwinOuwehand** [comment]
Hi,
Thank you for your feedback. 
Solution 5 is included in Solution 1, hence the filename Sol1and5.hs 

Also, exercise one specifically states: "subgrids with left-top corner (2,2), (2,6), (6,2), and (6,6) should also yield a surjective function."

No random deletion of hints was not mentioned as a requirement in the exercise.

**Comment by hdmeyer** [comment]
Grade of exercise 5 has been updated.

Random deletion is not stated, so your grade would be a 7 (since other groups implemented such things, or variations), but you missed the test report, so it is a 6.

**Comment by BertLisser** [comment]
Lab 6: 6a, 6b, 7

I cannot find your reports.

**Comment by stemis** [comment]
@BertLisser You are right, I had some git issues. I have re-uploaded Lab6
